### PR TITLE
bugfix: move unified_mode into resource definition

### PR DESCRIPTION
**Pull request by jasonwbarnett**
### Description

Fixes unified_mode deprecation warnings.

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
@lamont-granquist can you review this one? I think this is a pretty obvious fix.

**Comment by lamont-granquist** [comment]
This probably never should have been fixed this way.  We test this using non-unified_mode chef-clients and then pray that it'll work correctly on unified_mode and we can't support running it both ways, that's deeply crazy.

We need to remove this and find some other way of suppressing the deprecation warning.

**Comment by lamont-granquist** [comment]
And basically what adding this is doing is asking me to ultimately debug issues in this massively complex cookbook that needs backcompat to early-12 at least if not chef-11 and would then need to run in unfied_mode and not unified_mode keeping both execution models in my head, which is a large pile of 'nope'.  This cookbook needs to remain non-unified_mode.

**Comment by jasonwbarnett** [comment]
@lamont-granquist closing this out in favor of this: https://github.com/chef-cookbooks/chef_client_updater/pull/242

**Pull request closed without merging**
