### PR TITLE
change default to 'kill' from 'exec'

### PR DESCRIPTION
**Pull request by lamont-granquist**
kill seems to clean up a lot of garbage that exec would leave behind.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
see #45

**Comment by lamont-granquist** [comment]
i'm leaning towards this being the correct default for most people the problem is that it makes the cookbook less testable.

but the problem is that people should mostly be running interval mode in production and using 'kill', but can't test that mode without switching to 'exec' for test-kitchen runs which invalidates their testing.

the way to fix t-k tests of this cookbook would be to have some way to tell t-k that a killed chef-client process wasn't really a failure -- but for 99.9% of the rest of t-k test runs that condition absolutely has to be a failure.  and the whole point is that we're sending a signal to the process group to make the parent die, but then we want that signal to propagate to the pgrp and that'll kill the rest of the process tree including the running chef-client sending the signal.  we have exit code support in t-k but the point is we don't have any opportunity to return exit signals if we use kill.

in production we don't want to exit and then re-exec most of the time since we really want to clean up that parent process, and then have the ultimate supervisor (runit or systemd or whatever) give us another chef-client controlling process.

the exec support seems to be useful mostly to people who both fire off one-shot cronjobs in production and do not use interval runs.  in which case then you do get accurate testing, you get immediate runs after chef-client updates itself, etc.  that clearly causes all kinds of issues though with everyone else who does not follow that model.

so...    ¯\_(ツ)_/¯

**Comment by tas50** [comment]
Needs to have the exec set in the kitchen configs so that tests pass, but I approve the idea here.

**Comment by lamont-granquist** [comment]
A complicating factor to the whole design of this cookbook is that when we run chef-client without --no-fork on the command line it still creates a "supervisor" process and forks off a worker (which I've argued in the past was very confusing).

So its possible that the check to see if we're interval-running needs to more accurately look for the absence of --no-fork and switch to kill -- but that's probably the overwhelming use case.

I wouldn't be too surprised if TK doesn't run without --no-fork as well -- which would explain some of the times that I've seen this cookbook hang up (particularly on 11.6.x i think when all that forking and locking logic was undergoing an overhaul).

Leaning towards just doing kill...

The really nice thing about exec though is that you immediately run the new chef-client and converge it and get success afterwards.  When it works, its very slick to run it that way.  It just fails a lot and I don't know how to make it more resiliant.

Oh yeah, the user who wrote this was only considering interval runs because if we're not running in an interval then the supervisor will exit -- but where we get into issues is with buggy supervisors and locking issues that prevent the child from ever running in the first place...

I'm still inclined to do kill by default, but I haven't 100% convinced myself quite yet...

Once thing we could maybe do is re-exec with a different lockfile.  Hopefully nobody is trying to use this cookbook to "upgrade" to 11.6.0 so that we don't have to worry about the target version being busted old implementations of the locking code and we can just run a one shot with a different lockfile...  That might actually be better overall for everyone if it works...

**Comment by lamont-granquist** [comment]
Oh that doesn't address #45 at all which is the old supervisor process hanging around...

**Comment by lamont-granquist** [comment]
since chef-client runs forked by default and since chef-client 11.x was when we were developing that whole model and its all buggy and weird, we really need to default to `kill`.

**Comment by croffe** [comment]
I can safely say in the variety of configurations I've been running - kill has been more effective than exec.

**Comment by lamont-granquist** [comment]
@tas50 here you go

**Comment by tas50** [comment]
Sweet

**Pull request merged**
