### PR TITLE
Allow the specification of a constrained version

### LINKED ISSUE #7: Allow floating versions
### Cookbook version

:latest

### Chef-client version

12.19.36

### Platform Details

N/A

### Scenario:

Allow version specification such as "<13.0.0",  or "~>12.19" etc.

### Expected Result:

Available versions should be match using the known ruby version rules, and the latest version that matches installed.

### PR DESCRIPTION
**Pull request by Rarian**
### Description

This allows the option of specifying a constrained version using the [standard constraint syntax](https://docs.chef.io/cookbook_versions.html).

### Issues Resolved

#7 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by Rarian** [comment]
@tas50 Let me know if this needs any more work.

**Comment by lamont-granquist** [comment]
mixlib-install already supports versions like "12" which means "12.x.x" aka "~> 12.0"

**Comment by Rarian** [comment]
I've never been able to have anything but an infinite loop when specifying a version like "12". Anyway, feel free to close this and the corresponding issue if you like.

This was just something I picked to work on randomly at the hackathon.

**Comment by lamont-granquist** [comment]
its possible that functionality simply needs to be fixed.

**Comment by lamont-granquist** [comment]
yeah closing in favor of #17

**Comment by lamont-granquist** [comment]
infinite loop fixed in #22

**Pull request closed without merging**
